language: generic
sudo: required # when using docker
service:
    - docker

before_install:
    - docker build -t gfajardo95/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true gfajardo95/docker-react npm run test
